# Generated by Django 5.1.1 on 2024-09-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0004_exam_examresults_feecommitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
